### ISSUE TITLE
Set up authentication 

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-resource-registry#36] opened 2022-10-18 09:27 UTC
### Description

We need to set up authentication for the resource registry. 

The following have been decided

- Maskinporten token exchanged to an Altinn token will be used as an authentication mechanism when API is called from a resource owner
- Maskinporten token will be used calling from proxy in Altinn 2

Authentication of end users will be postponed to later. 

### Additional Information

Authorization is handled in #43 

Support for Maskinporten i JWTCookie authentication is added in 
https://github.com/Altinn/altinn-access-management/issues/187

### Tasks

- [ ] Configure authentication for an organization using maskinporten or Altinn token

### Acceptance Criterias

- [ ] Requires a valid altinn token from maskinporten or maskinporten

**Comment by jonkjetiloye** [comment] 2023-05-31 18:55
@annerisbakk @Sondre-B 
This is set to done in [Team Tilgangsinfo](https://github.com/orgs/Altinn/projects/75) but left in Test for [Team Tilgangsstyring & Kontroll](https://github.com/orgs/Altinn/projects/50) and the issue is not closed.

I'll leave it up to you to decide whether it's been tested and close the issue

**Closed** 2024-01-25 07:04 UTC
Labels: kind/user-story, refinement
